language: ruby
before_script:
- cp .env.example .env
script:
- gem install danger --no-ri --no-rdoc && danger
- bundle exec rake
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    rooms:
      secure: FNPQHroWM3P3fMsJn9B7TAT8kSt9oufV1u3K+FDmGoEtE0iIjD04Qmz97q7Vorzp38pZBC0JeAvhGiUiRBB5pJ7vvXlaF8vgoNYZGP1/iQkpNNEJNtcAyeF1t0PytSpvB8LCAdvp6Ql6uhMofVxaYJbCBGK7Jbwmo375ebEK5wLkasYIMF7zNAIUEkdxrPNneMFNJQFQOmuAFvJpOUnCs7+MTyroGeShRuSbXLbaFxIGqmMfTqKudA+rAH9y4/DJbbnp5Kp65Box2bmSQqaopr3iDbSmXbiNAopLgPyi0ZfHYvQnHmBi9ekZE+5Sq/HcEcA8v3GyEwYvXRi1i5nXrA+gosQCf38nQp/A+ukIprkELWEPWQUjH2MUJk2BS9Qr16ck0mA9IJv3iDy3S4wnoMH2FMfDH5IuYE47xSEoCjWeu+EjORCmLhCLGTS1mjQaVd0qa5uCf3a5jz5yf0vdIm7D1OEYVwCjV3W0zzdH0r2bEJa46rLTnbh3BCCW36ivBHaTgXQVu/Wtxq8e6a02CRcvstK9aNZOJJprlVLB2mbb6riFcLuEEdul7lGgExaulHzHU64y7CM4Yqz6Y+sGYXxm2YVfIsAYFUJ8RGBelK1VMIGiHZWC/PLAImwFMfpzNWHIXUEj+TBN6ack7W3SGzLwUTCDxglteuvQ6qblf54=
env:
  global:
    secure: f5Gfgy7T7Ml14Bhv2Y741Cx1UYjYbWEugYHXtHMkggdpQdG3CNcxU6tR58q7bs9XAYI8I5MNYJR1X04Dl/LxMnEldtUAO3y7Cjcwp3Zdp1WzAa4tj42le8qquslZb8BunEMvfhkSvwnyN6H5S/dRbbiF/DKVX5VPFrlkO87MvuBvEBZYVmnoSc7kzU2+luq0K7Hx1fdjD60FukoRFij9GZlfzP6riK/ixKsSp24CxWDfatQTCuEvT/PI6Sl32Ys+EZsiqtA+tMi9v36P6peB1nIkSZQagqQpOOPEQl6G1LrICbAQz2OPVNlvAdulv7CWCgoJW1yFmXavKt2ZOh2Iwz5Tyuy43LAS/nouPwPQllSYd7YC/1g0abD+Gy5W69i7Nwz6B7rjMiq79UmwWB8SccVwHE9qg8c/3ovGcSvwHKD49+aPvjnBI6I+SxoLYxU9xV5HMR1LDA8apl3/haZo652jviNZaZYRM3qyJU7f8XwQcYthLNgucdx6CdCwL6TcKNWY1nkX+R+NCLbKDZEx4O7J4CBJapbM7WB5YlhGNTzUZ7buRB+cd99aEDU0JlO0bn185xXFBju5INtCSeq2SWYlgWp9L4sbNvGV0YfHlN5IwhvntTx+NcU8HIzY1mFKowffPXB8kzFhqXK8sDUeaBnEniNfxCecUg11lzgi3A8=
